name: KinD Cluster
description: Creates KinD clusters
      
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install KinD
      shell: bash
      run: |
        sudo curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        sudo curl -Lo /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo chmod +x /usr/local/bin/kind /usr/local/bin/kubectl
    - name: Bring up KinD cluster
      shell: bash
      run: |
        if [ -f .kind-config.yaml ]; then
          kind create cluster --wait 300s --config=.kind-config.yaml
        else
          kind create cluster --wait 300s
        fi
        sleep 50
    - name: List KinD nodes
      shell: bash
      run: kubectl get nodes
